# Usar una imagen base de PHP con Apache
FROM php:8.2-apache

# Instalar dependencias necesarias
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    mariadb-server \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Habilitar el módulo de Apache para reescritura de URL
RUN a2enmod rewrite

# Copiar los archivos del proyecto al contenedor
COPY . /var/www/html/

# Cambiar permisos y propietario de los archivos
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html

# Establecer el directorio de trabajo
WORKDIR /var/www/html

# Exponer el puerto 80
EXPOSE 80

# Configurar MySQL
RUN service mysql start && \
    mysql -e "CREATE DATABASE sistema_agencia;" && \
    mysql -e "CREATE USER 'agencia_user'@'%' IDENTIFIED BY '123456';" && \
    mysql -e "GRANT ALL PRIVILEGES ON sistema_agencia.* TO 'agencia_user'@'%';" && \
    mysql -e "FLUSH PRIVILEGES;"

# Iniciar Apache y MySQL en segundo plano
CMD service mysql start && apache2-foreground
