version: '3.8'

services:
  web:
    build: .
    ports:
      - "90:90"  # Cambiado de 8081:80
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: sistema_agencia
      MYSQL_USER: agencia_user
      MYSQL_PASSWORD: 123456
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sistema_agencia
      MYSQL_USER: agencia_user
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

volumes:
  mysql_data:
