version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: sistema_agencia
      MYSQL_USER: agencia_user
      MYSQL_PASSWORD: AgenC!@x8rPz7LwQ
    depends_on:
      - db

  db:
    image: mysql:8.0
    # ❌ PUERTO 3306 EXPUESTO AL EXTERIOR — RECOMENDADO COMENTARLO EN PRODUCCIÓN
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RooT@92j!LmA34sY
      MYSQL_DATABASE: sistema_agencia
      MYSQL_USER: agencia_user
      MYSQL_PASSWORD: AgenC!@x8rPz7LwQ
    volumes:
      - mysql_data:/var/lib/mysql
    command: --log-bin-trust-function-creators=1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: RooT@92j!LmA34sY
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web

volumes:
  mysql_data:
