version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Mantener este mapeo para acceso directo si es necesario
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: sistema_agencia
      MYSQL_USER: agencia_user
      MYSQL_PASSWORD: 123456
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sistema_agencia
      MYSQL_USER: agencia_user
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  mysql_data:
